---
- name: 'This is main playbook'
  hosts: all
  gather_facts: True

  vars:
    var1: "param1"

  tasks:
    - name: "Transfer script.sh"
      copy:
        src: script.sh
        dest: /root/script.sh
        mode: 0755

    - name: 'Execute script.sh'
      shell: "/root/script.sh {{ var1 }} param2 param3"
      register: output

    - name: 'Debug var'
      debug:
        var: output

    - name: 'Debug msg'
      debug:
        msg: "There is param1 string inside"
      when: '"param1" in output.stdout'
