---
- name: "This is my first playbook"
  hosts: all

  tasks:
    - name: "My first task"
      ping:

    - name: "My 2nd task"
      ping:

    - name: "My 3rd task"
      ping:

    - name: "My 4th task"
      ping:
