---
- name: 'Test Vault'
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    secret_var: "vladimir"

  tasks:
    - name: 'Show vars'
      debug:
        msg: "{{ secret_var1 }}"
      ignore_errors: yes

    - name: 'Show var'
      debug:
        var: secret_var

    - name: Fail task when the command error output prints FAILED
      command: cat /etc/hostname
      register: command_result
      failed_when: "'N0762' not in command_result.stdout"

    - name: 'Executing date'
      shell: date
      changed_when: False
