---
- name: 'This is main playbook'
  hosts: all
  gather_facts: True

  var:
    var1: "param1"

  tasks:
    - name: "Transfer script.sh"
      copy:
        src: script.sh
        dest: /root/script.sh

    - name: 'Execute some command'
      shell: "/root/script.sh {{ var1 }} param2 param3"
      register: output

    - name: 'Debug var'
      debug:
        var: output

    - name: 'Debug msg'
      debug:
        msg: "There is server01 string inside"
      when: '"ser" in output.stdout'
