---
- name: 'This is main playbook'
  hosts: all
  gather_facts: True

  tasks:
    - name: 'Execute some command'
      shell: cat /etc/hostname
      register: output

    - name: 'Debug var'
      debug:
        var: output

    - name: 'Debug msg'
      debug:
        msg: "There is ansible string inside"
      when: 'ansible' in output.stdout
