---
- name: 'This is main playbook'
  hosts: all
  # gather_facts: True

  vars:
    test:
      - test1
      - test2
      - test3

  tasks:
    - name: 'Test loop with var containing list'
      debug:
        msg: "This is {{ item }}"
      with_items: "{{ test }}"

    - name: 'Test loop with list'
      debug:
        msg: "This is {{ item }}"
      with_items:
        - test1
        - test2
        - test3

    - name: 'Test loop with list of dicts'
      debug:
        msg: "This is name: {{ item.name }} and key: {{ item.key }}"
      with_items:
        - { name: vladimir, key: mykey}
        - { name: test1, key: mykey1}
        - { name: test2, key: mykey2}

    - name: 'Test nested loops with list of lists'
      debug:
        msg: "This is name: {{ item[0] }} and key: {{ item[1] }}"
      with_items:
        - [ 'alice', 'bob' ]
        - [ 'clientdb', 'employeedb', 'providerdb' ]
